### ISSUE TITLE
CAudio 2.3.0 won't compile in Visual Studio 2013

### ISSUE THREAD

**Issue by sunnystormy** [R4stl1n/cAudio#31]
Hello!

I keep getting "unresolved externals" errors while trying to compile CAudio in VS Express 2013.

Here's my log:

Error	28	error LNK2019: unresolved external symbol __imp_alSourceUnqueueBuffers referenced in function "private: void __cdecl cAudio::cAudioSource::empty(void)" (?empty@cAudioSource@cAudio@@AEAAXXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	25	error LNK2019: unresolved external symbol __imp_alSourceStop referenced in function "public: virtual __cdecl cAudio::cAudioSource::~cAudioSource(void)" (??1cAudioSource@cAudio@@UEAA@XZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	27	error LNK2019: unresolved external symbol __imp_alSourceQueueBuffers referenced in function "public: virtual bool __cdecl cAudio::cAudioSource::play(void)" (?play@cAudioSource@cAudio@@UEAA_NXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	24	error LNK2019: unresolved external symbol __imp_alSourcePlay referenced in function "public: virtual bool __cdecl cAudio::cAudioSource::play(void)" (?play@cAudioSource@cAudio@@UEAA_NXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	26	error LNK2019: unresolved external symbol __imp_alSourcePause referenced in function "public: virtual void __cdecl cAudio::cAudioSource::pause(void)" (?pause@cAudioSource@cAudio@@UEAAXXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	20	error LNK2019: unresolved external symbol __imp_alSourcei referenced in function "public: virtual bool __cdecl cAudio::cAudioSource::play2d(bool const &)" (?play2d@cAudioSource@cAudio@@UEAA_NAEB_N@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	18	error LNK2019: unresolved external symbol __imp_alSourcef referenced in function "public: __cdecl cAudio::cAudioSource::cAudioSource(class cAudio::IAudioDecoder *,class cAudio::IAudioDeviceContext *)" (??0cAudioSource@cAudio@@QEAA@PEAVIAudioDecoder@1@PEAVIAudioDeviceContext@1@@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	19	error LNK2019: unresolved external symbol __imp_alSource3f referenced in function "public: virtual void __cdecl cAudio::cAudioSource::move(class cAudio::cVector3 const &)" (?move@cAudioSource@cAudio@@UEAAXAEBVcVector3@2@@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	34	error LNK2019: unresolved external symbol __imp_alListenerfv referenced in function "public: virtual void __cdecl cAudio::cListener::setDirection(class cAudio::cVector3 const &)" (?setDirection@cListener@cAudio@@UEAAXAEBVcVector3@2@@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cListener.obj	cAudio
Error	32	error LNK2019: unresolved external symbol __imp_alListenerf referenced in function "public: virtual void __cdecl cAudio::cListener::setMasterVolume(float const &)" (?setMasterVolume@cListener@cAudio@@UEAAXAEBM@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cListener.obj	cAudio
Error	33	error LNK2019: unresolved external symbol __imp_alListener3f referenced in function "public: virtual void __cdecl cAudio::cListener::move(class cAudio::cVector3 const &)" (?move@cListener@cAudio@@UEAAXAEBVcVector3@2@@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cListener.obj	cAudio
Error	1	error LNK2019: unresolved external symbol __imp_alGetString referenced in function "protected: bool __cdecl cAudio::cAudioCapture::checkError(void)" (?checkError@cAudioCapture@cAudio@@IEAA_NXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioCapture.obj	cAudio
Error	23	error LNK2019: unresolved external symbol __imp_alGetSourcei referenced in function "private: void __cdecl cAudio::cAudioSource::empty(void)" (?empty@cAudioSource@cAudio@@AEAAXXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	22	error LNK2019: unresolved external symbol __imp_alGetSourcefv referenced in function "public: virtual class cAudio::cVector3 const __cdecl cAudio::cAudioSource::getDirection(void)const " (?getDirection@cAudioSource@cAudio@@UEBA?BVcVector3@2@XZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	21	error LNK2019: unresolved external symbol __imp_alGetSourcef referenced in function "public: virtual float const __cdecl cAudio::cAudioSource::getDopplerStrength(void)const " (?getDopplerStrength@cAudioSource@cAudio@@UEBA?BMXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	14	error LNK2019: unresolved external symbol __imp_alGetError referenced in function "public: __cdecl cAudio::cAudioSource::cAudioSource(class cAudio::IAudioDecoder *,class cAudio::IAudioDeviceContext *)" (??0cAudioSource@cAudio@@QEAA@PEAVIAudioDecoder@1@PEAVIAudioDeviceContext@1@@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	16	error LNK2019: unresolved external symbol __imp_alGenSources referenced in function "public: __cdecl cAudio::cAudioSource::cAudioSource(class cAudio::IAudioDecoder *,class cAudio::IAudioDeviceContext *)" (??0cAudioSource@cAudio@@QEAA@PEAVIAudioDecoder@1@PEAVIAudioDeviceContext@1@@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	29	error LNK2019: unresolved external symbol __imp_alGenBuffers referenced in function "public: __cdecl cAudio::cAudioSource::cAudioSource(class cAudio::IAudioDecoder *,class cAudio::IAudioDeviceContext *)" (??0cAudioSource@cAudio@@QEAA@PEAVIAudioDecoder@1@PEAVIAudioDeviceContext@1@@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	17	error LNK2019: unresolved external symbol __imp_alDeleteSources referenced in function "public: virtual __cdecl cAudio::cAudioSource::~cAudioSource(void)" (??1cAudioSource@cAudio@@UEAA@XZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	30	error LNK2019: unresolved external symbol __imp_alDeleteBuffers referenced in function "public: virtual __cdecl cAudio::cAudioSource::~cAudioSource(void)" (??1cAudioSource@cAudio@@UEAA@XZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	39	error LNK2019: unresolved external symbol __imp_alcOpenDevice referenced in function "public: virtual bool __cdecl cAudio::cOpenALDeviceContext::initialize(char const *,int,int)" (?initialize@cOpenALDeviceContext@cAudio@@UEAA_NPEBDHH@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cOpenALDeviceContext.obj	cAudio
Error	37	error LNK2019: unresolved external symbol __imp_alcMakeContextCurrent referenced in function "public: virtual bool __cdecl cAudio::cOpenALDeviceContext::initialize(char const *,int,int)" (?initialize@cOpenALDeviceContext@cAudio@@UEAA_NPEBDHH@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cOpenALDeviceContext.obj	cAudio
Error	35	error LNK2019: unresolved external symbol __imp_alcIsExtensionPresent referenced in function "public: __cdecl cAudio::cOpenALAudioDeviceList::cOpenALAudioDeviceList(enum cAudio::IDeviceType)" (??0cOpenALAudioDeviceList@cAudio@@QEAA@W4IDeviceType@1@@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cOpenALAudioDeviceList.obj	cAudio
Error	6	error LNK2019: unresolved external symbol __imp_alcGetString referenced in function "protected: bool __cdecl cAudio::cAudioCapture::initOpenALDevice(void)" (?initOpenALDevice@cAudioCapture@cAudio@@IEAA_NXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioCapture.obj	cAudio
Error	8	error LNK2019: unresolved external symbol __imp_alcGetIntegerv referenced in function "public: virtual void __cdecl cAudio::cAudioCapture::updateCaptureBuffer(bool)" (?updateCaptureBuffer@cAudioCapture@cAudio@@UEAAX_N@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioCapture.obj	cAudio
Error	4	error LNK2019: unresolved external symbol __imp_alcGetError referenced in function "protected: bool __cdecl cAudio::cAudioCapture::checkError(void)" (?checkError@cAudioCapture@cAudio@@IEAA_NXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioCapture.obj	cAudio
Error	38	error LNK2019: unresolved external symbol __imp_alcDestroyContext referenced in function "public: virtual bool __cdecl cAudio::cOpenALDeviceContext::initialize(char const *,int,int)" (?initialize@cOpenALDeviceContext@cAudio@@UEAA_NPEBDHH@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cOpenALDeviceContext.obj	cAudio
Error	36	error LNK2019: unresolved external symbol __imp_alcCreateContext referenced in function "public: virtual bool __cdecl cAudio::cOpenALDeviceContext::initialize(char const *,int,int)" (?initialize@cOpenALDeviceContext@cAudio@@UEAA_NPEBDHH@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cOpenALDeviceContext.obj	cAudio
Error	40	error LNK2019: unresolved external symbol __imp_alcCloseDevice referenced in function "public: virtual bool __cdecl cAudio::cOpenALDeviceContext::initialize(char const *,int,int)" (?initialize@cOpenALDeviceContext@cAudio@@UEAA_NPEBDHH@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cOpenALDeviceContext.obj	cAudio
Error	12	error LNK2019: unresolved external symbol __imp_alcCaptureStop referenced in function "public: virtual void __cdecl cAudio::cAudioCapture::stopCapture(void)" (?stopCapture@cAudioCapture@cAudio@@UEAAXXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioCapture.obj	cAudio
Error	11	error LNK2019: unresolved external symbol __imp_alcCaptureStart referenced in function "public: virtual bool __cdecl cAudio::cAudioCapture::beginCapture(void)" (?beginCapture@cAudioCapture@cAudio@@UEAA_NXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioCapture.obj	cAudio
Error	13	error LNK2019: unresolved external symbol __imp_alcCaptureSamples referenced in function "public: virtual void __cdecl cAudio::cAudioCapture::updateCaptureBuffer(bool)" (?updateCaptureBuffer@cAudioCapture@cAudio@@UEAAX_N@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioCapture.obj	cAudio
Error	9	error LNK2019: unresolved external symbol __imp_alcCaptureOpenDevice referenced in function "protected: bool __cdecl cAudio::cAudioCapture::initOpenALDevice(void)" (?initOpenALDevice@cAudioCapture@cAudio@@IEAA_NXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioCapture.obj	cAudio
Error	10	error LNK2019: unresolved external symbol __imp_alcCaptureCloseDevice referenced in function "protected: void __cdecl cAudio::cAudioCapture::shutdownOpenALDevice(void)" (?shutdownOpenALDevice@cAudioCapture@cAudio@@IEAAXXZ)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioCapture.obj	cAudio
Error	31	error LNK2019: unresolved external symbol __imp_alBufferData referenced in function "private: bool __cdecl cAudio::cAudioSource::stream(unsigned int)" (?stream@cAudioSource@cAudio@@AEAA_NI@Z)	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	2	error LNK2001: unresolved external symbol __imp_alGetString	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cAudioSource.obj	cAudio
Error	3	error LNK2001: unresolved external symbol __imp_alGetString	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cOpenALDeviceContext.obj	cAudio
Error	15	error LNK2001: unresolved external symbol __imp_alGetError	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cOpenALDeviceContext.obj	cAudio
Error	7	error LNK2001: unresolved external symbol __imp_alcGetString	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cOpenALAudioDeviceList.obj	cAudio
Error	5	error LNK2001: unresolved external symbol __imp_alcGetError	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\cOpenALDeviceContext.obj	cAudio
Error	41	error LNK1120: 35 unresolved externals	C:\Users\MichaelB\Desktop\Code\Libraries\cAudio-master\Build\cAudio\Release\cAudio.dll	cAudio

Is there something I'm missing? Any help would be appreciated.

Thank you!

**Comment by R4stl1n** [comment]
Ensure you are linking to the correct libraries for visual c++
