### ISSUE TITLE
Version libcAudio.so?

### ISSUE THREAD

**Issue by TC01** [R4stl1n/cAudio#40]
I'm looking into possibly packaging cAudio for Fedora.

It appears that you don't version libcAudio.so; would it be possible for you to start doing so upstream? Most downstream distributions want any shared libraries installed by packages to be versioned in order to better guarantee ABI compatibility; you can read Fedora's guidelines on the subject [here](https://fedoraproject.org/wiki/Packaging:Guidelines#Shared_Libraries).

cmake should make it [very easy](http://pusling.com/blog/?p=352) to version a library.

**Comment by R4stl1n** [comment]
Technically the project as a whole is versioned. 

Version 2.3.0 dev

**Comment by TC01** [comment]
Well, the point of versioning the .so files in addition to the entire project is to ensure that someone writing a library or game using cAudio can, at *compile time*, link against a specific version of the library rather than an arbitrary one. That means that if in a later release (2.4.0?) you break ABI compatibility with 2.3.0, you can increment the .so version and then people know they need to rebuild their projects. Does that make sense?

Distributions like Fedora want libraries they ship to do this so that we know when something depending on them needs to be rebuilt.

So you could, for example, in the CMake configuration for each standard library, set:

```
set_property(TARGET bar PROPERTY VERSION "2.3.0")
set_property(TARGET bar PROPERTY SOVERSION 2 )
```

And then increment when you release new versions that break ABI compatibility.

**Comment by ComradeKeys** [comment]
I have created a versioned .so binary in my fork of cAudio so this will hopefully be fixed with my pull request

**Comment by R4stl1n** [comment]
Just accepted this to allow for the SO versioning. Ill make a new release for 2.3.0 and close it out moving the brand to 2.4.0 dev.

**Comment by TC01** [comment]
Oh, awesome, thanks!

I guess this means I don't have to version downstream now. :)

**Comment by R4stl1n** [comment]
Having to fix a few branch compilation issues. Will have the new tag 2.3.1 release for you in a bit. just got it rebuilding on mac going to test on linux then create the tag.

**Comment by R4stl1n** [comment]
There you go hopefully that helps you out with it.

**Comment by TC01** [comment]
Thanks!

One thing though. I just realized that @ComradeKeys's patch was only for libcAudio.so itself. Any chance you could do the same for the two plugin .so files? It should just be a matter of copying the lines from cAudio/CMakeLists.txt into Plugins/*/CMakeLists.txt.

Sorry, I realize you just tagged a release! I can do it myself for now, or submit a PR, if you would prefer.
