### ISSUE TITLE
IManagerEventHandler not firing events

### ISSUE THREAD

**Issue by alreay** [R4stl1n/cAudio#48]
Hi all,
I've wrapped cAudio with a singleton manager that uses the audiomanager with the threaded update feature. 

The interface that I inherit from IManagerEventHandler.h includes the virtual functions that can be overridden like "onUpdate()" but cAudioManager.cpp never actually fires the events although it does handle them all.

The fix is very simple, just one line, and I'll be happy to create a pull request from what I've modified to make it work in my case. However, I'm curious to hear if there's something obvious that I've missed with how this is supposed to work or whether it's always been left unimplemented for some reason.

In case you're interested, my wrapper has a music playlist which needs to be advanced at the end of a song and does things like fade outs when notified by the game engine thread. That's why I need to get the update event firing.

Cheers and thanks for cAudio!

**Comment by R4stl1n** [comment]
I haven't heard about the IManagerEventHandler not firing events id love to see the pull request and figure out what is causing the issue.

**Comment by r4stl1n** [comment]
Looks like you took care of it. Merged in and thanks for finding it.
